# Generated by Django 2.0.2 on 2018-02-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0002_auto_20180224_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('first_name', 'last_name')},
        ),
    ]
