# Generated by Django 2.0.2 on 2018-02-23 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0003_auto_20180224_0015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('name', 'variant')},
        ),
    ]
