# Generated by Django 2.0.2 on 2018-02-23 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0004_auto_20180224_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racetime',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Game'),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Player'),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Track'),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.VehicleModel'),
        ),
    ]
