# Generated by Django 2.0.2 on 2018-02-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0005_auto_20180224_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='variant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
