# Generated by Django 2.0.2 on 2018-02-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0006_auto_20180224_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
