# Generated by Django 2.0.2 on 2018-02-24 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0007_auto_20180224_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='race_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Race date'),
        ),
    ]
