# Generated by Django 2.0.2 on 2018-02-26 03:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0008_auto_20180224_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('first_name', 'last_name', 'nickname')},
        ),
        migrations.AlterModelOptions(
            name='racetime',
            options={'ordering': ['-race_date_time', 'player']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('name', 'variant')},
        ),
        migrations.AlterModelOptions(
            name='vehiclemake',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ('make__name', 'name')},
        ),
    ]
