# Generated by Django 2.0.2 on 2018-02-26 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0009_auto_20180226_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('name',)},
        ),
    ]
