# Generated by Django 2.0.2 on 2018-03-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0011_auto_20180302_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='track',
            name='variant',
        ),
    ]
